### ISSUE TITLE
How to parse Quoted Quote?

### ISSUE THREAD

**Issue by joonhwan** [benjamin-hodgson/Pidgin#31] opened 2019-02-26 04:41 UTC
I'd like to parse something like 

```
"Hi I'm ""Joonhwan"""
```

to 

```
{quote} + {string:Hi I'm "Joonhwan"} + {quote} 
```

Please be noted that the 'joonhwan' part is quoted inside of the string. yes..wierd but I need this.
quote mark itself is escaped using quote.

How to I create parser for this ?

```
var result = Sequence('"', '"').Select(_ => '"').Or(Token(c => c!='"')).Many().Between(Char('"')).Parse("\"\"\"abcd\"\"1234.556\"");
```

That what i tried but failed.

**Comment by benjamin-hodgson** [comment] 2019-02-26 15:48
You're almost there. The problem is what happens when your parser encounters the single `"` at the end of the input. The first branch of the `Or`, `Sequence('"','"')`, consumes the `"`, so the parsing process commits to that branch. Then when it fails to see the second `"` it fails. Because it's committed to the left branch, it doesn't try the right branch and the whole parser fails.

You just need to apply the `Try` operator, which tells the parser "don't commit to this branch". When a `Try` parser fails, it backtracks so that another branch of the `Or` can be tried.

```csharp
Parser<char, string> parser = Try(String("\"\"")).ThenReturn('"')
    .Or(Token(c => c != '"'))
    .ManyString()
    .Between(Char('"'));
```

**Closed by benjamin-hodgson** 2019-02-26 15:48 UTC

**Comment by joonhwan** [comment] 2019-02-27 06:52
Thanks. your answers are always well organized and good literature as well as your library itself.
